#!/usr/bin/env python
import re
import sys
import textwrap

import cursive_re

example_line_re = cursive_re.compile(
    cursive_re.beginning_of_line() +
    cursive_re.one_or_more(cursive_re.text(" ")) +
    cursive_re.group((cursive_re.text(">>>") | cursive_re.text("..."))),
    re.MULTILINE
)


def main():
    print()
    print("## Reference")
    for name in cursive_re.__all__:
        print(f"### `cursive_re.{name}`")
        print()

        value = getattr(cursive_re, name)
        doc = value.__doc__
        doc_first_line, *doc_rest_lines = doc.split("\n")
        doc_dedented = doc_first_line + "\n" + textwrap.dedent("\n".join(doc_rest_lines))
        doc_dedented = example_line_re.sub(r"    \1", doc_dedented)
        print(doc_dedented)
    return 0


if __name__ == "__main__":
    sys.exit(main())
