#!/usr/bin/env python
import sys
import textwrap

import cursive_re


def main():
    print()
    print("## Reference")
    for name in cursive_re.__all__:
        print(f"### `cursive_re.{name}`")
        print()

        value = getattr(cursive_re, name)
        doc = value.__doc__
        doc_first_line, *doc_rest_lines = doc.split("\n")
        doc_dedented = doc_first_line + "\n" + textwrap.dedent("\n".join(doc_rest_lines))

        example_marker_passed = False
        for line in doc_dedented.split("\n"):
            if "Examples:" in line:
                example_marker_passed = True

            elif example_marker_passed and line.strip():
                line = f"  {line}"

            print(line)
    return 0


if __name__ == "__main__":
    sys.exit(main())
